version: 2
updates:
  - package-ecosystem: composer
    directory: /sdk/php
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(php)"

  - package-ecosystem: npm
    directory: /sdk/typescript
    schedule:
      interval: weekly
      day: monday
      time: "06:10"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(node)"

  - package-ecosystem: pip
    directory: /sdk/python
    schedule:
      interval: weekly
      day: monday
      time: "06:20"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(python)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Africa/Lagos
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(actions)"
